# Generated by Django 2.1 on 2019-03-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='¿Es posible...?', max_length=150, verbose_name='Pregunta')),
                ('answer', models.TextField(default='', max_length=500, verbose_name='Respuesta')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Pregunta frecuentes',
                'verbose_name_plural': 'Preguntas frecuentes',
            },
        ),
    ]
