# Generated by Django 2.1 on 2019-03-21 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carousel',
            options={'ordering': ['title'], 'verbose_name': 'Imagen del carrusel', 'verbose_name_plural': 'Imagenes del carrusel'},
        ),
        migrations.AlterField(
            model_name='carousel',
            name='image',
            field=models.ImageField(null=True, upload_to='Carousel'),
        ),
    ]
