# Generated by Django 2.1 on 2019-03-21 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0002_auto_20190321_0058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carousel',
            options={'ordering': ['-title'], 'verbose_name': 'Imagen del carrusel', 'verbose_name_plural': 'Imagenes del carrusel'},
        ),
    ]
