# Generated by Django 2.1 on 2019-03-13 23:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publications', '0002_auto_20190311_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shopping_basketItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Cantidad')),
                ('customer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('publication', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='publications.Publication', verbose_name='Publicación')),
            ],
        ),
    ]
