# Generated by Django 2.1 on 2019-03-14 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_basket', '0002_auto_20190313_1805'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopping_basketitem',
            options={'verbose_name': 'Carrito de compras', 'verbose_name_plural': 'Carritos de compras'},
        ),
        migrations.AlterField(
            model_name='shopping_basketitem',
            name='quantity',
            field=models.SmallIntegerField(default=10, verbose_name='Cantidad'),
        ),
    ]
