# Generated by Django 2.1 on 2019-03-14 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_basket', '0003_auto_20190313_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopping_basketitem',
            name='quantity',
            field=models.SmallIntegerField(default=1, verbose_name='Cantidad'),
        ),
    ]
