# Generated by Django 2.1 on 2019-03-14 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_basket', '0007_auto_20190313_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping_basketitem',
            name='price',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=8, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='shopping_basketitem',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Cantidad'),
        ),
    ]
