# Generated by Django 2.1 on 2019-03-14 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_basket', '0008_auto_20190313_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopping_basketitem',
            name='price',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=8, verbose_name='Precio por unidad'),
        ),
    ]
