# Generated by Django 2.1 on 2019-03-14 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_basket', '0009_auto_20190313_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopping_basketitem',
            name='price',
        ),
    ]
