# Generated by Django 2.1 on 2019-03-07 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
        ('wish_list', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WishlistItem',
            new_name='Wish_listItem',
        ),
    ]
