# Generated by Django 2.1 on 2019-03-07 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wish_list', '0002_auto_20190307_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish_listitem',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
        migrations.RemoveField(
            model_name='wish_listitem',
            name='publication',
        ),
        migrations.AddField(
            model_name='wish_listitem',
            name='publication',
            field=models.ManyToManyField(to='publications.Publication', verbose_name='Wish list'),
        ),
    ]
