# Generated by Django 2.1 on 2019-03-07 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
        ('wish_list', '0003_auto_20190307_0327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish_listitem',
            name='publication',
        ),
        migrations.AddField(
            model_name='wish_listitem',
            name='publication',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='publications.Publication', verbose_name='Wish list'),
        ),
    ]
