# Generated by Django 2.1 on 2019-03-07 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wish_list', '0004_auto_20190307_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish_listitem',
            name='publication',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='publications.Publication', unique=True, verbose_name='Wish list'),
        ),
    ]
