# Generated by Django 2.1 on 2019-03-09 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wish_list', '0005_auto_20190307_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish_listitem',
            name='publication',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='publications.Publication', verbose_name='Publicación'),
        ),
    ]
