# Generated by Django 2.1 on 2019-03-14 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wish_list', '0007_auto_20190313_1805'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wish_listitem',
            options={'verbose_name': 'Lista de deseos', 'verbose_name_plural': 'Listas de deseos'},
        ),
    ]
