# Generated by Django 2.1 on 2019-03-25 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_auto_20190325_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='get_subcategories', to='publications.SubCategory', verbose_name='Subcategoría'),
        ),
    ]
