# Generated by Django 2.1 on 2019-03-14 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_auto_20190313_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='price',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=8, verbose_name='Precio por unidad'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='stock',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='Cantidad'),
        ),
    ]
