# Generated by Django 2.1 on 2019-03-25 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_auto_20190325_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='parentCategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='publications.Category', verbose_name='Categoría padre'),
        ),
    ]
