# Generated by Django 2.1 on 2019-03-17 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0006_auto_20190316_2057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'categoria', 'verbose_name_plural': 'categorías'},
        ),
    ]
