# Generated by Django 2.1 on 2019-03-21 07:13

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Privacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Política de privacidad', max_length=200, verbose_name='Título')),
                ('content', ckeditor.fields.RichTextField(default='', verbose_name='Contenido')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Política de privacidad',
                'verbose_name_plural': 'Políticas de privacidad',
            },
        ),
    ]
