# Generated by Django 2.1 on 2019-03-26 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'ordering': ['created', 'updated', 'subtotal'], 'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='price',
            new_name='subtotal',
        ),
    ]
